export const SKILL_LEVELS = {
  ADVANCED: 'ADVANCED',
  PROFICIENT: 'PROFICIENT',
  DEVELOPING: 'DEVELOPING',
  NOVICE: 'NOVICE',
}

export const PROGRAMMING_SCOPES = {
  BACK_END: 'BACK_END',
  FRONT_END: 'FRONT_END',
  FULL_STACK: 'FULL_STACK',
}
