export { default as backgrKeyword } from './backgr-keyword.jpg'
export { default as fullstack } from './fullstack.jpg'
export { default as javascript } from './javascript1.png'
export { default as over10years } from './over10years.svg'
export { default as gmailLogo } from './gmailLogo.png'
export { default as skypeLogo } from './skypeLogo.png'
